version: "3"
services:
  mongo:
    image: mongo
    container_name: crudrest.mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017